//
//  GitIncludeService.swift
//  Switzy
//
//  Created by Yefga on 08/09/2026
//

import Foundation

enum GitIncludeError: LocalizedError {
    case writeFailed(String)
    case ruleFailed(String)

    var errorDescription: String? {
        switch self {
        case .writeFailed(let detail):
            return "Failed to write the profile git config: \(detail)"
        case .ruleFailed(let detail):
            return "Failed to update the folder rule: \(detail)"
        }
    }
}

/// Manages per-directory git identity through git's own `includeIf` conditional
/// includes. Each profile owns a gitconfig file; a rule points a directory at
/// that file, so git resolves the identity per repository — in every terminal
/// and IDE, and whether or not Switzy is running.
actor GitIncludeService {

    private let shell = ShellService()
    private let fileManager = FileManager.default

    private var profilesDirectoryURL: URL {
        fileManager.homeDirectoryForCurrentUser
            .appendingPathComponent(".config/switzy/profiles")
    }

    func configURL(for profile: GitProfile) -> URL {
        profilesDirectoryURL.appendingPathComponent("\(profile.id.uuidString).gitconfig")
    }

    // MARK: - Profile Config File

    /// Write the gitconfig that a profile's directory rules include.
    @discardableResult
    func writeConfigFile(for profile: GitProfile) throws -> URL {
        let url = configURL(for: profile)

        do {
            try fileManager.createDirectory(
                at: profilesDirectoryURL,
                withIntermediateDirectories: true
            )
            try renderConfig(for: profile).write(to: url, atomically: true, encoding: .utf8)
        } catch {
            throw GitIncludeError.writeFailed(error.localizedDescription)
        }

        return url
    }

    func removeConfigFile(for profile: GitProfile) {
        try? fileManager.removeItem(at: configURL(for: profile))
    }

    private func renderConfig(for profile: GitProfile) -> String {
        var lines = [
            "# Generated by Switzy. Edits are overwritten when the profile changes.",
            "[user]",
            "\tname = \(profile.userName)",
            "\temail = \(profile.userEmail)"
        ]

        if let signingKey = profile.signingKey, !signingKey.isEmpty {
            lines.append("\tsigningkey = \(signingKey)")
            lines.append("[gpg]")
            lines.append("\tformat = ssh")
            lines.append("[commit]")
            lines.append("\tgpgsign = true")
        }

        if let sshKeyPath = profile.sshKeyPath, !sshKeyPath.isEmpty {
            lines.append("[core]")
            lines.append("\tsshCommand = ssh -i \(expandTilde(in: sshKeyPath))")
        }

        return lines.joined(separator: "\n") + "\n"
    }

    // MARK: - Rules

    /// Point every directory the profile claims at its config file.
    func applyRules(for profile: GitProfile) async throws {
        let rules = profile.resolvedDirectoryRules
        guard !rules.isEmpty else {
            removeConfigFile(for: profile)
            return
        }

        let configURL = try writeConfigFile(for: profile)

        for directory in rules {
            try await addRule(directory: directory, configPath: configURL.path)
        }
    }

    func addRule(directory: String, configPath: String) async throws {
        do {
            _ = try await shell.run(
                "git",
                arguments: ["config", "--global", includeKey(for: directory), configPath]
            )
        } catch {
            throw GitIncludeError.ruleFailed(error.localizedDescription)
        }
    }

    func removeRule(directory: String) async {
        _ = try? await shell.run(
            "git",
            arguments: ["config", "--global", "--unset", includeKey(for: directory)]
        )
    }

    /// Drop every rule that points at this profile, then its config file.
    func removeAllRules(for profile: GitProfile) async {
        for directory in profile.resolvedDirectoryRules {
            await removeRule(directory: directory)
        }
        removeConfigFile(for: profile)
    }

    /// Directories currently carrying a rule, whatever profile they point at.
    func currentRuleDirectories() async -> [String] {
        guard let output = try? await shell.run(
            "git",
            arguments: ["config", "--global", "--name-only", "--get-regexp", "^includeIf\\."]
        ) else {
            return []
        }

        return output
            .components(separatedBy: .newlines)
            .compactMap(directory(fromKey:))
    }

    // MARK: - Private Helpers

    /// `includeIf.gitdir:<dir>/.path` — the key git itself uses, so rules are
    /// written and removed with `git config` rather than by editing ~/.gitconfig.
    private func includeKey(for directory: String) -> String {
        "includeIf.gitdir:\(normalized(directory)).path"
    }

    private func directory(fromKey key: String) -> String? {
        let trimmed = key.trimmingCharacters(in: .whitespaces)
        // git normalises the section name to lowercase on read ("includeif"),
        // while the subsection keeps the case it was written with.
        let prefix = "includeif.gitdir:"
        guard
            trimmed.lowercased().hasPrefix(prefix),
            trimmed.hasSuffix(".path")
        else {
            return nil
        }

        let start = trimmed.index(trimmed.startIndex, offsetBy: prefix.count)
        let end = trimmed.index(trimmed.endIndex, offsetBy: -".path".count)
        guard start < end else { return nil }
        return String(trimmed[start..<end])
    }

    /// A `gitdir:` pattern ending in `/` matches every repository beneath it.
    private func normalized(_ directory: String) -> String {
        let expanded = expandTilde(in: directory)
        return expanded.hasSuffix("/") ? expanded : expanded + "/"
    }

    private func expandTilde(in path: String) -> String {
        guard path == "~" || path.hasPrefix("~/") else { return path }

        let homeDirectory = fileManager.homeDirectoryForCurrentUser
        if path == "~" {
            return homeDirectory.path
        }

        let relativePath = String(path.dropFirst(2))
        return homeDirectory.appendingPathComponent(relativePath).path
    }
}
